### ISSUE TITLE
19.03.2 crash

### ISSUE THREAD

**Issue by xiangfeidexiaohuo** [joshuaseltzer/YTHoldForSpeed#14]

**Comment by joshuaseltzer** [comment]
Fixed with the latest commits. 1.1.2 will be live on Havoc soon (probably today).

**Comment by xiangfeidexiaohuo** [comment]
> Fixed with the latest commits. 1.1.2 will be live on Havoc soon (probably today).

Haha, I have already used it. When I saw you updated the source code, I compiled it directly.

**Comment by joshuaseltzer** [comment]
> > Fixed with the latest commits. 1.1.2 will be live on Havoc soon (probably today).
> 
> Haha, I have already used it. When I saw you updated the source code, I compiled it directly.

Great! Thanks for confirming it's working.
