### ISSUE TITLE
Possible to integrate with YTSpeed to speedup beyond 2x?

### ISSUE THREAD

**Issue by huynhxloi** [joshuaseltzer/YTHoldForSpeed#15]
First of all I love this tweak! Such a great QOL tweak that I've used a lot since learning about it. Right now it's limited to 2x speed. My question is if it's possible to have options beyond 2x or have it integrated with YTSpeed (which goes to 5x)? Thanks again for the great work.

**Comment by joshuaseltzer** [comment]
The latest commits to the `main` branch (and 1.2.0 that will be released on Havoc in the next day or so) will include this suggestion.
