### ISSUE TITLE
Localization for YTHoldForSpeed from my fork.

### ISSUE THREAD

**Issue by arichornlover** [joshuaseltzer/YTHoldForSpeed#17]
Hey @joshuaseltzer sorry to mention you here but I am telling you about some localization I recommend bringing over to your Repository of YTHoldForSpeed. Because it seems that some users did some pull requests to my forked repository by mistake.

Here they are.

**Portuguese** Localization - by [VictorxD70](https://github.com/VictorxD70)
https://github.com/aricloverEXALT/YTHoldForSpeed/pull/1

**Indonesian** Localization - by [okkidwi](https://github.com/okkidwi)
https://github.com/aricloverEXALT/YTHoldForSpeed/pull/2

Feel free to close this issue once you are done! 😄

**Comment by joshuaseltzer** [comment]
Thanks for the heads up! This is easy so I'll get these integrated and push a new release shortly.
